name: Build Testing Container Package v2

on:
  workflow_dispatch:
  push:
    paths:
    - '!.github/**'

jobs:
  build-test-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 20.11.9
          #- 21.08.8-2
          #- 22.05.5

    env:
      base_tag:     ghcr.io/eth-cscs/slurm-container-${{ matrix.version }}:latest
      tag:          ghcr.io/eth-cscs/slurm-uenv-mount-tester-${{ matrix.version }}:latest
      cache_tag:    ghcr.io/eth-cscs/cache_docker/slurm-uenv-mount-tester-${{ matrix.version }}:latest

      cache_file:   slurm-uenv-mount-tester-${{ matrix.version }}_latest.tar.gz
      user_flags:   -u testuser -w /home/testuser
      NODE_HW:      CPUS=2

    steps:
# ------------------------------------------------------------------------
#  Build the host container and plugin
# ------------------------------------------------------------------------
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build production image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ci/Dockerfile
        push: true
        tags: ${{ env.cache_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
                
  run-tests:
    needs: build-test-image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - 20.11.9
          #- 21.08.8-2
          #- 22.05.5    
          
    container:
      image: ghcr.io/eth-cscs/cache_docker/slurm-uenv-mount-tester-${{ matrix.version }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        NODE_HW: CPUS=2
      options: --cpus 2

    steps:
      - uses: actions/checkout@v3
      - name: Compile plugin
        run: |
          CPPFLAGS=-I$SLURM_ROOT/include meson setup --prefix=$SLURM_ROOT /build . \
          && ninja install -C /build \
          && echo "required $SLURM_ROOT/lib64/libslurm-uenv-mount.so" > $SLURM_ROOT/etc/plugstack.conf

#    - name: Load Image
#      run: docker load < ${{ env.cache_file }}
   
#    - name: Start Docker Container
#      run: |
#        ID=$(docker run --detach --privileged -e NODE_HW=${{ env.NODE_HW }} -t ${{ env.tag }})
#        echo "ID=$ID" >> $GITHUB_ENV
      
#    - name: Run Tests
#      run: |
#        ID=$(docker run --privileged -e NODE_HW=${{ env.NODE_HW }} -t ${{ env.tag }} run_tests)
#        docker exec ${{ env.user_flags }} ${{ env.ID }} /testuser-entrypoint.sh make tests

# ------------------------------------------------------------------------
#  Publish the complete container and the plugin itself
# ------------------------------------------------------------------------
#    - name: Push Docker Image
#      run: docker push ${{ env.tag }}
