name: Build Testing Container Package v2

on:
  workflow_dispatch:
  push:
    paths:
    - '!.github/**'

jobs:
  build-test-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 20.11.9
          #- 21.08.8-2
          #- 22.05.5

    env:
      base_tag:     ghcr.io/eth-cscs/slurm-container-${{ matrix.version }}:latest
      cache_tag:    ghcr.io/eth-cscs/cache_docker/slurm-uenv-mount-tester-${{ matrix.version }}:latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build tester image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ci/Dockerfile
        push: true
        tags: ${{ env.cache_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: 
          DOCKER_CONTAINER=${{ env.base_tag }}
                
  run-tests:
    needs: build-test-image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - 20.11.9
          #- 21.08.8-2
          #- 22.05.5    
          
    container:
      image: ghcr.io/eth-cscs/cache_docker/slurm-uenv-mount-tester-${{ matrix.version }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        NODE_HW: CPUS=2
      options: --cpus 2

    steps:
      - uses: actions/checkout@v3
      #- run: make -f ci/Makefile build install
      #- run: make -f ci/Makefile test
      
      - run: make rpm
      
      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          name: slurm-uenv-mount-${{ matrix.version }}
          tag_name: slurm-uenv-mount-${{ matrix.version }}
          files: |
            /usr/local/lib64/libslurm-uenv-mount.so
            rpm/SRPMS/*
            rpm/RPMS/*

#    - name: Load Image
#      run: docker load < ${{ env.cache_file }}
   
#    - name: Start Docker Container
#      run: |
#        ID=$(docker run --detach --privileged -e NODE_HW=${{ env.NODE_HW }} -t ${{ env.tag }})
#        echo "ID=$ID" >> $GITHUB_ENV
      
#    - name: Run Tests
#      run: |
#        ID=$(docker run --privileged -e NODE_HW=${{ env.NODE_HW }} -t ${{ env.tag }} run_tests)
#        docker exec ${{ env.user_flags }} ${{ env.ID }} /testuser-entrypoint.sh make tests

# ------------------------------------------------------------------------
#  Publish the complete container and the plugin itself
# ------------------------------------------------------------------------
#    - name: Push Docker Image
#      run: docker push ${{ env.tag }}
