name: Release plugin RPM

on:
  workflow_dispatch:

jobs:
  rpm:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/eth-cscs/slurm-container-test:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: lsb_release && ls && pwd
