name: Test plugin

on:
  workflow_dispatch:
  registry_package:
    types: [published]


env:
  TAG: ghcr.io/eth-cscs/slurm-uenv-mount:latest
  NODE_HW: CPUS=2

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Start Docker Container
      run: |
        ID=$(docker run --detach --privileged -e NODE_HW=${{ env.NODE_HW }} -t ${{ env.TAG }})
        echo "ID=$ID" >> $GITHUB_ENV
    - name: Run srun, ls on mount
      run: |
        docker exec -u testuser -w /home/testuser ${{ env.ID }} /testuser-entrypoint.sh \
          srun -t 00:00:30 --uenv-mount-file=fs.sqfs ls
    - name: Run srun, ls /user-environment
      run: |
        docker exec -u testuser -w /home/testuser ${{ env.ID }} /testuser-entrypoint.sh \
          srun -t 00:00:30 --uenv-mount-file=fs.sqfs ls /user-environment
        
      #run: docker run -t ${{ env.TAG }} \
      #  bash -c "\
      #    sinfo; \
      #    srun -t 00:00:30 --uenv-mount-file=0.1.105.tar.gz ls
      #  "
      
#    - name: Upload library
#      uses: softprops/action-gh-release@v1
#      with:
#        name: libslurm-uenv-mount-$SLURM_VERSION.so
#
#   - name:
#     run: zypper install -y rpm-build
#   - name: clone
#     uses: actions/checkout@v2
#   - name: build-srpm
#     run: |
#       make rpm
#       sudo rpmbuild --rebuild "$(find rpm/SRPMS -name '*.rpm' -type f -print -quit)" --define "_topdir $(pwd)/rpm"
#       sudo rpm --install "$(find rpm/RPMS -name '*.rpm' -type f -print -quit)"
#       find rpm -name '*.rpm' -type f -exec cp {} . \;
#   - name: upload-rpm        
#     uses: actions/upload-artifact@v3
#     with:
#       name: rpm
#       path: '*.rpm'
