name: slurm
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    container:
      image: simonpzh/slurm-20.11.9
      # args: --entrypoint=./entrypoint.sh
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
         zypper install -y python3-pip squashfs sudo
         python3 -m pip install --upgrade pip \
         && python3 -m pip install meson ninja

         CPPFLAGS=-I$SLURM_ROOT/include meson setup builddir
         ninja install -C builddir

         echo "required /lib64/libslurm-uenv-mount.so" \
         > $SLURM_ROOT/etc/plugstack.conf

         whoami
          # start slurm
         /start-slurm.sh

         # switch to testuser
         set -x
         useradd testuser
         cat /etc/passwd
         mkdir -p /home/testuser && chown -R testuser /home/testuser

         # create a squashfs file
         su testuser -c sh <<\EOF
         dd=$(mktemp -d)
         (
             umask 022
             cd "$dd" || exit
             mkdir test
             echo "This is file A" >> test/fileA.txt
             mkdir -p test/testdir
         )
         mksquashfs "$dd" /home/testuser/fs.sqfs -noappend
         EOF

      - name: check
        run: |
          sudo -u testuser sinfo
